/**************************************************************************
 *
 * Recursive Descent mdu definition file.
 *
 */

 /**
 *
 *  @file cmRecursiveDescent.h
 *
 *  This file defines the Recursive Descent mdu.
 *
 *  This class simulates the Recursive Descent used for recursive descent
 *  rasterization in a GPU.
 *
 */

#ifndef _RECURSIVEDESCENT_

#define _RECUSRIVEDESCENT_

#include "GPUType.h"
#include "cmMduBase.h"
#include "Signal.h"
#include "GPUReg.h"
#include "support.h"
#include "bmRasterizer.h"
#include "cmTileEvaluator.h"
#include "cmRasterizerState.h"
#include "cmRasterizerCommand.h"
#include "cmTileInput.h"
#include "cmFragmentInput.h"
#include "cmTriangleSetupOutput.h"

namespace arch
{


//**  Stamp tile level (lowest tile level).  
static const U32 STAMPLEVEL = 1;

//**  Maximum number of tiles that can be generated from a top level tile.  
static const U32 MAXGENERATEDTILES = 4;

/**
 *
 *  This class implements the Recursive Descent simulation mdu.
 *
 *  The Recursive Descent mdu simulates the Recursive Descent hardware
 *  used for recursive descent rasterization in a GPU.
 *
 *  This class inherits from the cmoMduBase class that offers basic simulation
 *  support.
 *
 */

class RecursiveDescent : public cmoMduBase
{
private:

    //  Recursive Descent signals.  
    Signal *rastCommand;        //  Rasterizer command signal from the Rasterizer main mdu.  
    Signal *rastState;          //  Rasterizer state signal to the Rasterizer main mdu.  
    Signal *newTriangle;        //  New setup triangle signal from Triangle Setup.  
    Signal *triangleRequest;    //  Triangle request signal to Triangle Setup.  
    Signal **evaluateTile;      //  Evaluate tile signal to the Tile Evaluators.  
    Signal **newTiles;          //  New tile signals from the Tile Evaluators.  
    Signal **newFragment;       //  New fragment signals from the Tile Evaluators.  
    Signal **evaluatorState;    //  State signal from the Tile Evaluators.  
    Signal *hzData;             //  Data signal from the Hierarchical Z Buffer.  
    Signal *interpolator;       //  Fragment signal to the Interpolator.  
    Signal *interpolatorState;  //  State signal from the Interpolator.  

    //  Recursive Descent state.  
    RasterizerState state;      //  Current state of the Recursive Descent mdu.  
    TileEvaluatorState *tileEvalStates; //  Current state of the Tile Evaluators connected to the mdu.  
    RasterizerCommand *lastRSCommand;   //  Stores the last Rasterizer Command received (for signal tracing).  
    U32 triangleCounter;     //  Number of received setup triangles.  
    bool lastTriangle;          //  Last batch triangle received flag.  
    U32 topLevel;            //  Current top tile level/size based in the current viewport size.  

    //  Recursive Descent registers.  

    //  Recursive Descent parameters.  
    bmoRasterizer &bmRast;//  Reference to the rasterizer behaviorModel used by Recursive Descent.  
    U32 triangleFIFOSize;    //  Size of the setup triangle FIFO.  
    U32 numTileEvaluators;   //  Number of Tile evaluators connected to the Recursive Descent.  
    U32 tilesCycle;          //  Tiles that can be received per cycle from each Tile Evaluator.  
    U32 tileStackSize;       //  Size of the Tile Stack (entries) for Recursive Descent.  
    U32 stampFragments;      //  Number of fragments per stamp (lowest level tile).  
    U32 stampsCycle;         //  Number of stamps per cycle to send down the pipeline.  
    U32 fragmentBufferSize;  //  Size (entries) of the fragment buffer.  
    char **tileEvalPrefixes;    //  Array with the Tile Evaluators prefixes.  

    //  Recursive Descent Triangle FIFO.  
    TriangleSetupOutput **triangleFIFO; //  Setup triangle FIFO where to store triangles pending for rasterization.  
    U32 firstTriangle;   //  Pointer to the first available triangle in the Setup Triangle FIFO.  
    U32 nextFreeSTEntry; //  Pointer to the next free entry in the Setup Triangle FIFO.  
    U32 storedTriangles; //  Number of triangles stored in the Setup Triangle FIFO.  

    //  Recursive Descent Tile Stack.  
    TileInput ***tileStack; //  Tile Stack that stores the remaining tiles to be evaluated by the Tile Evaluators.  
    U32 *nextTile;       //  Pointer to the next (last) tile in the Tile Stack.  
    U32 *storedTiles;    //  Total number of stored tiles.  
    U32 *reservedTiles;  //  Reserved tile stack entries counter.  
    U32 totalStored;     //  Total stored tiles in the tile stacks counter.  
    U32 totalReserved;   //  Total reserved tile entries in the tile stacks counter.  

    //  Recursive Descent Fragment Buffer.  
    FragmentInput **fragmentBuffer; //  Fragment buffer storing the fragments generated by the Tile Evaluators at the lowest tile level.  
    U32 firstFragment;           //  First fragment in the buffer.  
    U32 storedFragments;         //  Number of fragments in the buffer.  
    U32 nextFreeFBEntry;         //  Next free entry in the fragment buffer.  

    //  Private functions.  

    /**
     *
     *  Processes a rasterizer command.
     *
     *  @param command The rasterizer command to process.
     *  @param cycle  Current simulation cycle.
     *
     */

    void processCommand(RasterizerCommand *command, U64 cycle);

    /**
     *
     *  Processes a register write.
     *
     *  @param reg The Triangle Traversal register to write.
     *  @param subreg The register subregister to writo to.
     *  @param data The data to write to the register.
     *
     */

    void processRegisterWrite(GPURegister reg, U32 subreg, GPURegData data);


public:

    /**
     *
     *  Recursive Descent constructor.
     *
     *  Creates and initializes a new Recursive Descent mdu.
     *
     *  @param bmRast Reference to the rasterizer behaviorModel to be used
     *  to emulate rasterization operations.
     *  @param triangleFIFOSize Size of the setup triangle FIFO in the
     *  Recursive Descent hardware.
     *  @param numTileEvaluators Number of Tile Evaluators connected to the
     *  Recursive Descent.
     *  @param tilesCycleEvaluator Number of Tiles that can be received from
     *  each Tile Evaluator per cycle.
     *  @param tileStackSize Size of the Tile Stack in the Recursive Descent
     *  hardware.
     *  @param stampFragments Number of fragments per stamp (lowest level tile).
     *  @param stampsCycle Number of stamps per cycle to send down the pixel
     *  pipeline.
     *  @param fragmentBufferSize  Size of the fragment buffer.
     *  @param tileEvalPrefix Pointer to an array of Tile Evaluator name
     *  prefixes.
     *  @param name Name of the mdu.
     *  @param parent Parent mdu of the mdu.
     *
     *  @return A new initialized Recursive Descent mdu.
     *
     */

    RecursiveDescent(bmoRasterizer &bmRast, U32 triangleFIFOSize,
        U32 numTileEvaluators,  U32 tilesCyclesEvaluator,
        U32 tileStackSize, U32 stampFragments, U32 stampsCycle,
        U32 fragmentBufferSize, char **tileEvalPrefix,
        char *name, cmoMduBase* parent);

    /**
     *
     *  Recursive Descent simulation rutine.
     *
     *  Simulates a cycle of the Recursive Descent mdu.
     *
     *  @param cycle The cycle to simulate of the Recursive Descent mdu.
     *
     */

    void clock(U64 cycle);

};

} // namespace arch

#endif
