/**************************************************************************
 *
 */

#ifndef GAL_STORED_ITEM_ID_H
    #define GAL_STORED_ITEM_ID_H

#include "GALConstantLimits.h"
#include "GPUReg.h"

namespace libGAL
{

/**
 * Storable/restorable state identifiers
 */ 
enum GAL_STORED_ITEM_ID
{
    ///////////////////
    // Rasterization //
    ///////////////////

    GAL_RASTER_FIRST_ID = 0,
    
    GAL_RASTER_FILLMODE         =   GAL_RASTER_FIRST_ID,
    GAL_RASTER_CULLMODE         =   GAL_RASTER_FIRST_ID + 1,
    GAL_RASTER_VIEWPORT         =   GAL_RASTER_FIRST_ID + 2,
    GAL_RASTER_FACEMODE         =   GAL_RASTER_FIRST_ID + 3,
    GAL_RASTER_INTERPOLATION    =   GAL_RASTER_FIRST_ID + 4,
    GAL_RASTER_SCISSOR_TEST     =   GAL_RASTER_INTERPOLATION + cg1gpu::MAX_FRAGMENT_ATTRIBUTES,
    GAL_RASTER_SCISSOR_X        =   GAL_RASTER_SCISSOR_TEST + 1,
    GAL_RASTER_SCISSOR_Y        =   GAL_RASTER_SCISSOR_TEST + 2,
    GAL_RASTER_SCISSOR_WIDTH    =   GAL_RASTER_SCISSOR_TEST + 3,
    GAL_RASTER_SCISSOR_HEIGHT   =   GAL_RASTER_SCISSOR_TEST + 4,

    GAL_RASTER_PROPERTIES_COUNT = 10 + cg1gpu::MAX_FRAGMENT_ATTRIBUTES,

    GAL_RASTER_LAST =   GAL_RASTER_FIRST_ID + GAL_RASTER_PROPERTIES_COUNT,


    //////////////
    // ZStencil //
    //////////////

    GAL_ZST_FIRST_ID = GAL_RASTER_LAST,

    GAL_ZST_Z_ENABLED                   =   GAL_ZST_FIRST_ID,
    GAL_ZST_Z_FUNC                      =   GAL_ZST_FIRST_ID + 1,
    GAL_ZST_Z_MASK                      =   GAL_ZST_FIRST_ID + 2,
    GAL_ZST_STENCIL_ENABLED             =   GAL_ZST_FIRST_ID + 3,
    GAL_ZST_STENCIL_BUFFER_DEF          =   GAL_ZST_FIRST_ID + 4,
    GAL_ZST_FRONT_STENCIL_OPS           =   GAL_ZST_FIRST_ID + 5,
    GAL_ZST_FRONT_COMPARE_FUNC          =   GAL_ZST_FIRST_ID + 6,
    GAL_ZST_FRONT_STENCIL_REF_VALUE     =   GAL_ZST_FIRST_ID + 7,
    GAL_ZST_FRONT_STENCIL_COMPARE_MASK  =   GAL_ZST_FIRST_ID + 8,
    GAL_ZST_BACK_STENCIL_OPS            =   GAL_ZST_FIRST_ID + 9,
    GAL_ZST_BACK_COMPARE_FUNC           =   GAL_ZST_FIRST_ID + 10,
    GAL_ZST_BACK_STENCIL_REF_VALUE      =   GAL_ZST_FIRST_ID + 11,
    GAL_ZST_BACK_STENCIL_COMPARE_MASK   =   GAL_ZST_FIRST_ID + 12,
    GAL_ZST_RANGE_NEAR                  =   GAL_ZST_FIRST_ID + 13,
    GAL_ZST_RANGE_FAR                   =   GAL_ZST_FIRST_ID + 14,
    GAL_ZST_D3D9_DEPTH_RANGE            =   GAL_ZST_FIRST_ID + 15,
    GAL_ZST_SLOPE_FACTOR                =   GAL_ZST_FIRST_ID + 16, 
    GAL_ZST_UNIT_OFFSET                 =   GAL_ZST_FIRST_ID + 17,
    GAL_ZST_DEPTH_UPDATE_MASK           =   GAL_ZST_FIRST_ID + 18, 

    GAL_ZST_PROPERTIES_COUNT = 18,

    GAL_ZST_LAST = GAL_ZST_FIRST_ID + GAL_ZST_PROPERTIES_COUNT,


    //////////////
    // Blending //
    //////////////
    
    GAL_BLENDING_FIRST_ID       =   GAL_ZST_LAST,

    GAL_BLENDING_ENABLED        =   GAL_BLENDING_FIRST_ID,
    // ... Implicit enums for render targets 1, 2, ..., up to GAL_MAX_RENDER_TARGETS - 1

    GAL_BLENDING_SRC_RGB                =       GAL_BLENDING_FIRST_ID + GAL_MAX_RENDER_TARGETS,
    GAL_BLENDING_DST_RGB                =       GAL_BLENDING_SRC_RGB + 1,
    GAL_BLENDING_FUNC_RGB               =       GAL_BLENDING_SRC_RGB + 2,
    GAL_BLENDING_SRC_ALPHA              =       GAL_BLENDING_SRC_RGB + 3,
    GAL_BLENDING_DST_ALPHA              =       GAL_BLENDING_SRC_RGB + 4,
    GAL_BLENDING_FUNC_ALPHA             =       GAL_BLENDING_SRC_RGB + 5,
    GAL_BLENDING_COLOR                  =       GAL_BLENDING_SRC_RGB + 6,
    GAL_BLENDING_COLOR_WRITE_ENABLED    =       GAL_BLENDING_SRC_RGB + 7,
    GAL_BLENDING_COLOR_MASK_R           =       GAL_BLENDING_SRC_RGB + 8,
    GAL_BLENDING_COLOR_MASK_G           =       GAL_BLENDING_SRC_RGB + 9,
    GAL_BLENDING_COLOR_MASK_B           =       GAL_BLENDING_SRC_RGB + 10,
    GAL_BLENDING_COLOR_MASK_A           =       GAL_BLENDING_SRC_RGB + 11,

    GAL_BLENDING_PROPERTIES_COUNT = 12 + GAL_MAX_RENDER_TARGETS,

    GAL_BLENDING_LAST = GAL_BLENDING_FIRST_ID + GAL_BLENDING_PROPERTIES_COUNT,

    //////////////
    //  Stream  //
    //////////////

    GAL_STREAM_FIRST_ID     =   GAL_BLENDING_LAST,

    GAL_STREAM_ELEMENTS     =   GAL_STREAM_FIRST_ID,
    GAL_STREAM_FREQUENCY    =   GAL_STREAM_FIRST_ID + 1,
    GAL_STREAM_DATA_TYPE    =   GAL_STREAM_FIRST_ID + 2,
    GAL_STREAM_D3D9_COLOR   =   GAL_STREAM_FIRST_ID + 3,
    GAL_STREAM_STRIDE       =   GAL_STREAM_FIRST_ID + 4,
    GAL_STREAM_BUFFER       =   GAL_STREAM_FIRST_ID + 5,

    GAL_STREAM_PROPERTIES_COUNT = 5,

    GAL_STREAM_LAST = GAL_STREAM_FIRST_ID + GAL_STREAM_PROPERTIES_COUNT,



    //////////////
    // Sampler  //
    //////////////

    GAL_SAMPLER_FIRST_ID     =  GAL_STREAM_LAST,

    GAL_SAMPLER_ENABLED         =   GAL_SAMPLER_FIRST_ID,
    GAL_SAMPLER_CLAMP_S         =   GAL_SAMPLER_FIRST_ID + 1,
    GAL_SAMPLER_CLAMP_T         =   GAL_SAMPLER_FIRST_ID + 2,
    GAL_SAMPLER_CLAMP_R         =   GAL_SAMPLER_FIRST_ID + 3,
    GAL_SAMPLER_NON_NORMALIZED  =   GAL_SAMPLER_FIRST_ID + 4,
    GAL_SAMPLER_MIN_FILTER      =   GAL_SAMPLER_FIRST_ID + 5,
    GAL_SAMPLER_MAG_FILTER      =   GAL_SAMPLER_FIRST_ID + 6,
    GAL_SAMPLER_ENABLE_COMP     =   GAL_SAMPLER_FIRST_ID + 7,
    GAL_SAMPLER_COMP_FUNCTION   =   GAL_SAMPLER_FIRST_ID + 8,
    GAL_SAMPLER_SRGB_CONVERSION =   GAL_SAMPLER_FIRST_ID + 9,
    GAL_SAMPLER_MIN_LOD         =   GAL_SAMPLER_FIRST_ID + 10,
    GAL_SAMPLER_MAX_LOD         =   GAL_SAMPLER_FIRST_ID + 11,
    GAL_SAMPLER_MAX_ANISO       =   GAL_SAMPLER_FIRST_ID + 12,
    GAL_SAMPLER_LOD_BIAS        =   GAL_SAMPLER_FIRST_ID + 13,
    GAL_SAMPLER_UNIT_LOD_BIAS   =   GAL_SAMPLER_FIRST_ID + 14,
    GAL_SAMPLER_TEXTURE         =   GAL_SAMPLER_FIRST_ID + 15,

    GAL_SAMPLER_PROPERTIES_COUNT = 15,

    GAL_SAMPLER_LAST = GAL_SAMPLER_FIRST_ID + GAL_SAMPLER_PROPERTIES_COUNT,



    //////////////
    //  Device  //
    //////////////

    GAL_DEVICE_FIRST_ID    =    GAL_SAMPLER_LAST,
    
    GAL_DEV_PRIMITIVE                   =   GAL_DEVICE_FIRST_ID,    
    GAL_DEV_CURRENT_COLOR               =   GAL_DEVICE_FIRST_ID + 1,
    GAL_DEV_HIERARCHICALZ               =   GAL_DEVICE_FIRST_ID + 2,
    GAL_DEV_STREAM_START                =   GAL_DEVICE_FIRST_ID + 3,
    GAL_DEV_STREAM_COUNT                =   GAL_DEVICE_FIRST_ID + 4,
    GAL_DEV_STREAM_INSTANCES            =   GAL_DEVICE_FIRST_ID + 5,
    GAL_DEV_INDEX_MODE                  =   GAL_DEVICE_FIRST_ID + 6,
    GAL_DEV_EARLYZ                      =   GAL_DEVICE_FIRST_ID + 7,
    GAL_DEV_VERTEX_THREAD_RESOURCES     =   GAL_DEVICE_FIRST_ID + 8,
    GAL_DEV_FRAGMENT_THREAD_RESOURCES   =   GAL_DEVICE_FIRST_ID + 9,
    GAL_DEV_VSH                         =   GAL_DEVICE_FIRST_ID + 10,
    GAL_DEV_FSH                         =   GAL_DEVICE_FIRST_ID + 11,
    GAL_DEV_FRONT_BUFFER                =   GAL_DEVICE_FIRST_ID + 12,
    GAL_DEV_BACK_BUFFER                 =   GAL_DEVICE_FIRST_ID + 13,
    GAL_DEV_VERTEX_ATTRIBUTE_MAP        =   GAL_DEVICE_FIRST_ID + 14, 
    GAL_DEV_VERTEX_OUTPUT_ATTRIBUTE     =   GAL_DEV_VERTEX_ATTRIBUTE_MAP + cg1gpu::MAX_VERTEX_ATTRIBUTES ,
    GAL_DEV_FRAGMENT_INPUT_ATTRIBUTES   =   GAL_DEV_VERTEX_OUTPUT_ATTRIBUTE + cg1gpu::MAX_VERTEX_ATTRIBUTES,


    GAL_DEV_PROPERTIES_COUNT = 15 + cg1gpu::MAX_VERTEX_ATTRIBUTES + cg1gpu::MAX_VERTEX_ATTRIBUTES + cg1gpu::MAX_FRAGMENT_ATTRIBUTES,

    GAL_DEV_LAST = GAL_DEVICE_FIRST_ID + GAL_DEV_PROPERTIES_COUNT,
    // ... Put here new state item identifiers

    GAL_LAST_STATE = GAL_DEV_LAST,
};

} // namespace libGAL

#endif // GAL_STORED_ITEM_ID_H
